- hosts: all
  gather_facts: false
  remote_user: root
  tasks:
    - name: Create directory
      file:
        name: "/srv/www/lantian.pub"
        state: directory

    - name: Deploy website file
      synchronize:
        src: public/
        dest: /srv/www/lantian.pub/
        checksum: yes
        delete: yes
