on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build web pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup GitHub Actions cache for Nix
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: false

      - name: Cache WebP Images
        id: cache-webp
        uses: actions/cache@v4
        with:
          path: img_cache
          key: img_cache-${{ github.sha }}
          restore-keys: |
            img_cache-

      - name: Install npm dependencies
        run: |
          nix develop --command npm install

      - name: Build website files
        run: |
          nix develop --command npm run build

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git rsync

      - name: Rsync files over SSH
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > $HOME/.ssh/id_ed25519
          echo "StrictHostKeyChecking no" > $HOME/.ssh/config
          chmod -R 500 $HOME/.ssh

          sudo apt-get install -y rsync
          rsync -azr --delete-after -e "ssh -p2222" dist/ ci@rsync-ci.xuyh0120.win:/www/lantian.pub/

          sudo rm -rf $HOME/.ssh

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Remove precompressed files
        run: |
          find dist/ -name \*.gz -or -name \*.br -or -name \*.zst -delete

      - name: Deploy to lantian1998.github.io
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: |
          git config --global user.email "lantian-bot@lantian.pub"
          git config --global user.name "Lan Tian Bot"
          git config --global init.defaultBranch master

          pushd dist

          git init
          git add .
          git commit -m "Auto update: $(date -Iseconds)" --quiet
          git remote add origin https://xddxdd-bot:${{ secrets.AUTOMERGE_TOKEN }}@github.com/lantian1998/lantian1998.github.io.git
          git push -u origin master --force

          rm -rf .git
          popd
