on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build web pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Cache WebP Images
        id: cache-webp
        uses: actions/cache@v4
        with:
          path: img_cache
          key: img_cache

      - name: Install dependencies
        run: sudo apt-get install build-essential git gzip brotli zstd parallel rsync imagemagick libvips-dev python3

      - run: npm install

      - run: npm run build

      - run: npm run build-webp

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
