on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-node@v4
        with:
          node-version: lts
          cache: npm

      - name: Build web page
        run: |
          sudo apt-get install build-essential git gzip brotli zstd parallel rsync imagemagick libvips-dev python3
          npm install
          npm run build
          npm run build-webp

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
